### ISSUE TITLE
INVALID_BODY_HASH

### ISSUE THREAD

**Issue by imiten** [Mastercard/client-encryption-python#11]
Hi,

I am trying to run MDES tokenize api against sandbox as below and getting error for hash mismatch.  I am attaching the code so if any one can help debug.  I am not sharing keys.

./tokenize.sh 
{
  "Errors": {
    "Error": [
      {
        "Source": "Gateway",
        "ReasonCode": "INVALID_BODY_HASH",
        "Description": "The provided oauth_body_hash does not match the SHA256 hash of the request payload. Calculated: 8gvc07EIynBEDNsawysKl3cd+LbHDylpYlDiaX0Rbz8=, Received: 01NcCrM7J5FOzJrJiGs+5+UMnkZ5S5iveHoxY3inu+A=",
        "Recoverable": false,
        "Details": null
      }
    ]
  }
[code.txt](https://github.com/Mastercard/client-encryption-python/files/7642349/code.txt)

}

**Comment by jaaufauvre** [comment]
Hi @imiten, 

The raw payload sent on the wire must be exactly the same as the one passed to `OAuth.get_authorization_header`. From the code you shared, it looks like the payload is written to a file before being read and sent by the `curl` command.

In short, you should make sure: SHA256(encrypted_request_payload) == SHA256(tokenpayloadenc.json content) == SHA256(payload sent by cURL).

**Comment by imiten** [comment]
Hi,

Thanks for guidance.  I have attempted below.

I used json.dumps to store to file in mc_oauth.py and overwrite file always:

import os, json
f = open("tokenpayloadenc.json", "w")
#f.write(str(payload))
f.write(json.dumps(payload))
#json.dump(payload, f, ensure_ascii=False)
f.close()

I used --data-binary instead of -d in curl command and get below error now.  I did get your suggestions and thus went to check how get_authorization_header is using payload and found its using json.dumps so I did same for above save to file.  Now in curl I thought --data-binary is way to read it to prevent any data conversion.

{"errorCode":"CRYPTOGRAPHY_ERROR","errorDescription":"Cryptography Error","errors":[{"source":"INPUT","reasonCode":"CRYPTOGRAPHY_ERROR","description":"Cryptography Error"}],"responseId":"123456","supportsAuthentication":false}

**Comment by jaaufauvre** [comment]
Hi @imiten,

This `CRYPTOGRAPHY_ERROR` (occurring when trying to decrypt the payload) means you solved the `INVALID_BODY_HASH` error you had before (returned when verifying the OAuth signature and the payload integrity).

Since this is about integrating with MDES, and not a bug in this project, I would suggest to use https://developer.mastercard.com/support. The support team should be able to assist you.

**Comment by imiten** [comment]
The cryptography error was issue with field config.  For sandbox you have to hardcode the fingerprint as per:
https://developer.mastercard.com/mdes-digital-enablement/documentation/tutorials/create-a-new-project/ section 6 you see 243E6992EA467F1CBB9973FACFCC3BF17B5CD007.  Also the field config needs to be modified for it as:

{
  "paths": {
    "$": {
      "toEncrypt": {
        "fundingAccountInfo.encryptedPayload.encryptedData": "fundingAccountInfo.encryptedPayload"
      },
      "toDecrypt": {
        "fundingAccountInfo.encryptedPayload": "fundingAccountInfo.encryptedPayload.encryptedData"
      }
    }
  },
  "ivFieldName": "iv",
  "encryptedKeyFieldName": "encryptedKey",
  "encryptedValueFieldName": "encryptedData",
  "dataEncoding": "hex",
  "encryptionCertificate": "./MCD_Sandbox_MitenCardTokenization_API_Keys/sandbox.crt",
  "decryptionKey": "./MCD_Sandbox_MitenCardTokenization_API_Keys/sandboxprivate.key",
  "oaepPaddingDigestAlgorithm": "SHA-256",
  "oaepPaddingDigestAlgorithmFieldName": "oaepHashingAlgorithm",
  "encryptionKeyFingerprintFieldName": "publicKeyFingerprint",
  "encryptionKeyFingerprint" : "243E6992EA467F1CBB9973FACFCC3BF17B5CD007"
}

And the cert and key also need to be used from portal page shown in above from section 6.

For Delete API though for some reason same oauth logic is not working.  Python api probably needs to see how java api client is using it and figure out.

**Comment by jaaufauvre** [comment]
Hi @imiten,

Thanks for the follow-up. I'm going to forward this information to the relevant team in case the tutorial you are referring to can be improved.

For the non-working delete, are you saying there is an issue when using Client Encryption Python with `POST/digitization/static/1/0/delete`? If yes, can you please open an issue in this project using the "Bug report" template?

Thanks!

**Comment by imiten** [comment]
for non-working delete I meant issue with oauth project and not client encryption one.  I will check it out with mastercard support and update you here.
