### ISSUE TITLE
[BUG] Client Encryption Lib doesn't accept decryption key

### ISSUE THREAD

**Issue by raefezzeldin** [Mastercard/client-encryption-python#21]
#### Bug Report Checklist

- [ ] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?

**Description**
I am trying to invoke FLD Mastercard Submit API, I am using field level encryption lib in order to encrypt a the following payload on sandbox env and I am getting internal server error, and after checking with master card team they told me that they are getting an error: decryption key is missing in the request hoewever it exists in the config payload:
`{
    "paths": {"$": {"toEncrypt": {"$": "$"}, "toDecrypt": {"$": "$"}}},
    "ivFieldName": "iv",
    "encryptedKeyFieldName": "encryptedKey",
    "encryptedValueFieldName": "encryptedValue",
    "oaepPaddingDigestAlgorithmFieldName": "oaepPaddingDigestAlgorithm",
    "oaepPaddingDigestAlgorithm": "SHA256",
    "dataEncoding": "hex",
    "decryptionKey": "Path/to/p12.file",
    "decryptionKeyPassword": "keystorepassword",
    "encryptionCertificate": "path/to/pemfile",
    "encryptionKeyFingerprintFieldName": "encryptionKeyFingerprint",
    "encryptionKeyFingerprint": "FINGEPRINT",
    "encryptionCertificateFingerprintFieldName": "encryptionCertificateFingerprint",
    "encryptionCertificateFingerprint": "FINGERPRINT",
}
`

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**
I have used the same keys in the developed java application and it worked fine, however I didn't provide the decryption key in the config payload, as it is not required for this endpoints
`https://sandbox.api.mastercard.com/fld/confirmed-frauds/mastercard-frauds`

**Related issues/PRs**
Has a similar issue/PR been reported/opened before?
No
**Suggest a fix/enhancement**
If you can't fix the bug yourself, perhaps you can point to what might be causing the problem (line of code or commit), or simply make a suggestion.

**Comment by NehaSony** [comment]
Hi @raefezzeldin 

Would it be possible to share the reference app so that we can better reproduce the issue?
